game-settings:
  allow-victory-before-completing-game: false
  give-blindness-in-game-3: true
  per-arena-chat: true
  send-player-to-lobby-on-join: true
  spawn-fireworks-on-win: true
  min-players: 2
  max-players: 12
  starting-time: 30
  finishing-time: 5
  game-time:
    "1": 60
    "3": 60
    "6": 60
    "7": 600
  rewards:
    - "say {winner} is the winner!"
    - "eco give {winner} 10"
  sounds:
    player-loss-game: CAT_HIT
    player-pass-game: LEVELUP
    player-death: EXPLODE
    arena-starting: CLICK
    arena-countdown: NOTE_PLING
    arena-start: ORB_PICKUP
    green-light: GHAST_MOAN
    red-light: BLAZE_HIT
    glass-break: GLASS
  # For 1.13+
  # sounds:
  #    player-loss-game: ENTITY_CAT_HURT
  #    player-pass-game: ENTITY_PLAYER_LEVELUP
  #    player-death: ENTITY_GENERIC_EXPLODE
  #    arena-starting: UI_BUTTON_CLICK
  #    arena-countdown: BLOCK_NOTE_BLOCK_PLING
  #    arena-start: ENTITY_EXPERIENCE_ORB_PICKUP
  #    green-light: ENTITY_GHAST_AMBIENT
  #    red-light: ENTITY_BLAZE_HURT
  #    grass-break: BLOCK_GLASS_BREAK

lobby:
  world: ""
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0